k

diff --git a/.github/workflows/release-stub.yml b/.github/workflows/release-stub.yml
--- a/.github/workflows/release-stub.yml
+++ b/.github/workflows/release-stub.yml
@@ -38,4 +38,4 @@ jobs:
 
       - name: make sure github tag matches package version
         if: ${{ env.TAG_VERSION }} != ${{ env.PACKAGE_VERSION }} 
-        run: echo "Failure: Tag version, ${TAG_VERSION}, does not match package.json version, ${PACKAGE_VERSION}" && exit 1 
+        run: echo "Failure: Tag version, ${TAG_VERSION}, does not match package.json version, ${PACKAGE_VERSION}" & exit 1 
