f

diff --git a/.github/workflows/release-stub.yml b/.github/workflows/release-stub.yml
--- a/.github/workflows/release-stub.yml
+++ b/.github/workflows/release-stub.yml
@@ -22,8 +22,8 @@ jobs:
       - name: Run a one-line script
         run: echo "building a release based on tag, ${GITHUB_REF}"
 
-      - name: Set GH_TAG
-        run: echo "GH_TAG=$(echo ${GITHUB_REF#refs/tags/v})"
+      - name: Set TAG_VERSION
+        run: echo "TAG_VERSION=$(echo ${GITHUB_REF#refs/tags/v})" >> GITHUB_ENV
         id: extract_tag
 
       - name: Get version from package.json
@@ -33,4 +33,6 @@ jobs:
           path: 'package.json'
           prop_path: 'version'
 
-      - run: echo ${{steps.package_version.outputs.prop}} 
+      - name: make sure github tag matches package version
+        if: ${{ env.TAG_VERSION }} != ${{ steps.package_version.outputs.prop }} 
+        run: echo "Failure: Tag version, ${{ $env.TAG_VERSION }}, does not match package.json version, ${{ steps.package_version.outputs.prop }}" && exit 1 
